### PR TITLE
Do not merge into alias nodes or allow inserts on top of them

### LINKED ISSUE #7: Module does not work in Windows (was: Not able to install the module via metacpan.org)
When I try to install the module MaxMind::DB::Writer in my local system by command:

**cpanm MaxMind::DB::Writer**

It is failing.

I am pasting the build.log file which is generated while installing. Seems like the file **tree.c** have some errors.

---------------**build.log**---------------------
cpanm (App::cpanminus) 1.7004 on perl 5.018002 built for MSWin32-x64-multi-thread
Work directory is C:\Users\manish.m/.cpanm/work/1406179481.5480
You have make C:\strawberry\c\bin\dmake.exe
You have LWP 6.05
Falling back to Archive::Tar 1.96
Searching MaxMind::DB::Writer on cpanmetadb ...
--> Working on MaxMind::DB::Writer
Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/MaxMind-DB-Writer-0.050005.tar.gz
-> OK
Unpacking MaxMind-DB-Writer-0.050005.tar.gz
Entering MaxMind-DB-Writer-0.050005
Checking configure dependencies from META.json
Checking if you have Module::Build 0.3601 ... Yes (0.4205)
Checking if you have Module::Build 0.36 ... Yes (0.4205)
Configuring MaxMind-DB-Writer-0.050005
Running Build.PL
Checking for unsigned __int128... yes
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'MaxMind-DB-Writer' version '0.050005'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Devel::Dwarn 0 ... Yes (undef)
Checking if you have Data::Printer 0 ... Yes (0.35)
Checking if you have List::AllUtils 0 ... Yes (0.08)
Checking if you have constant 0 ... Yes (1.27)
Checking if you have Encode 0 ... Yes (2.59)
Checking if you have bytes 0 ... Yes (1.04)
Checking if you have Test::Deep::NoTest 0 ... Yes (undef)
Checking if you have Digest::MD5 0 ... Yes (2.53)
Checking if you have warnings 0 ... Yes (1.18)
Checking if you have Sereal::Encoder 0 ... Yes (3.001)
Checking if you have Digest::SHA1 0 ... Yes (2.13)
Checking if you have MaxMind::DB::Metadata 0 ... Yes (0.031003)
Checking if you have Test::Bits 0 ... Yes (0.02)
Checking if you have Test::More 0.88 ... Yes (1.001003)
Checking if you have Scalar::Util 0 ... Yes (1.38)
Checking if you have ExtUtils::CBuilder 0 ... Yes (0.280216)
Checking if you have Net::Works::Network 0.16 ... Yes (0.18)
Checking if you have Math::Int128 0.06 ... Yes (0.13)
Checking if you have Net::Works::Address 0 ... Yes (0.18)
Checking if you have Test::Requires 0 ... Yes (0.07)
Checking if you have XSLoader 0 ... Yes (0.16)
Checking if you have Module::Build 0.3601 ... Yes (0.4205)
Checking if you have namespace::autoclean 0 ... Yes (0.19)
Checking if you have File::Temp 0 ... Yes (0.2304)
Checking if you have utf8 0 ... Yes (1.10)
Checking if you have MooseX::StrictConstructor 0 ... Yes (0.19)
Checking if you have Test::Fatal 0 ... Yes (0.013)
Checking if you have Carp 0 ... Yes (1.3301)
Checking if you have lib 0 ... Yes (0.63)
Checking if you have IO::Handle 0 ... Yes (1.34)
Checking if you have Exporter 0 ... Yes (5.68)
Checking if you have Moose 0 ... Yes (2.1204)
Checking if you have Test::MaxMind::DB::Common::Data 0 ... Yes (0.031003)
Checking if you have Moose::Util::TypeConstraints 0 ... Yes (2.1204)
Checking if you have Net::Works 0.16 ... Yes (0.18)
Checking if you have MaxMind::DB::Role::Debugs 0 ... Yes (0.031003)
Checking if you have List::Util 0 ... Yes (1.38)
Checking if you have MaxMind::DB::Reader::Decoder 0 ... Yes (0.050005)
Checking if you have Data::Dumper::Concise 0 ... Yes (2.022)
Checking if you have strict 0 ... Yes (1.07)
Checking if you have autodie 0 ... Yes (2.25)
Checking if you have MaxMind::DB::Common 0.031003 ... Yes (0.031003)
Checking if you have Data::IEEE754 0 ... Yes (0.01)
Building and testing MaxMind-DB-Writer-0.050005
Building MaxMind-DB-Writer
gcc -c -I"c" -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fno-strict-aliasing -mms-bitfields -std=c99 -fms-extensions -Wall -g -s -O2 -I"C:\strawberry\perl\lib\CORE" -I"C:\strawberry\c\include" -o "c\perl_math_int128.o" "c\perl_math_int128.c"
In file included from C:\strawberry\perl\lib\CORE/sys/socket.h:180:0,
                 from C:\strawberry\perl\lib\CORE/win32.h:381,
                 from C:\strawberry\perl\lib\CORE/win32thread.h:4,
                 from C:\strawberry\perl\lib\CORE/perl.h:2869,
                 from c\perl_math_int128.c:11:
C:\strawberry\perl\lib\CORE/win32.h:386:26: warning: "/*" within comment [-Wcomment]
C:\strawberry\perl\lib\CORE/win32.h:387:33: warning: "/*" within comment [-Wcomment]
In file included from C:\strawberry\perl\lib\CORE/win32thread.h:4:0,
                 from C:\strawberry\perl\lib\CORE/perl.h:2869,
                 from c\perl_math_int128.c:11:
C:\strawberry\perl\lib\CORE/win32.h:386:26: warning: "/*" within comment [-Wcomment]
C:\strawberry\perl\lib\CORE/win32.h:387:33: warning: "/*" within comment [-Wcomment]
gcc -c -I"c" -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fno-strict-aliasing -mms-bitfields -std=c99 -fms-extensions -Wall -g -s -O2 -I"C:\strawberry\perl\lib\CORE" -I"C:\strawberry\c\include" -o "c\perl_math_int64.o" "c\perl_math_int64.c"
In file included from C:\strawberry\perl\lib\CORE/sys/socket.h:180:0,
                 from C:\strawberry\perl\lib\CORE/win32.h:381,
                 from C:\strawberry\perl\lib\CORE/win32thread.h:4,
                 from C:\strawberry\perl\lib\CORE/perl.h:2869,
                 from c\perl_math_int64.c:11:
C:\strawberry\perl\lib\CORE/win32.h:386:26: warning: "/*" within comment [-Wcomment]
C:\strawberry\perl\lib\CORE/win32.h:387:33: warning: "/*" within comment [-Wcomment]
In file included from C:\strawberry\perl\lib\CORE/win32thread.h:4:0,
                 from C:\strawberry\perl\lib\CORE/perl.h:2869,
                 from c\perl_math_int64.c:11:
C:\strawberry\perl\lib\CORE/win32.h:386:26: warning: "/*" within comment [-Wcomment]
C:\strawberry\perl\lib\CORE/win32.h:387:33: warning: "/*" within comment [-Wcomment]
gcc -c -I"c" -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fno-strict-aliasing -mms-bitfields -std=c99 -fms-extensions -Wall -g -s -O2 -I"C:\strawberry\perl\lib\CORE" -I"C:\strawberry\c\include" -o "c\tree.o" "c\tree.c"
In file included from C:\strawberry\perl\lib\CORE/sys/socket.h:180:0,
                 from C:\strawberry\perl\lib\CORE/win32.h:381,
                 from C:\strawberry\perl\lib\CORE/win32thread.h:4,
                 from C:\strawberry\perl\lib\CORE/perl.h:2869,
                 from c\tree.h:2,
                 from c\tree.c:1:
C:\strawberry\perl\lib\CORE/win32.h:386:26: warning: "/*" within comment [-Wcomment]
C:\strawberry\perl\lib\CORE/win32.h:387:33: warning: "/*" within comment [-Wcomment]
In file included from C:\strawberry\perl\lib\CORE/win32thread.h:4:0,
                 from C:\strawberry\perl\lib\CORE/perl.h:2869,
                 from c\tree.h:2,
                 from c\tree.c:1:
C:\strawberry\perl\lib\CORE/win32.h:386:26: warning: "/*" within comment [-Wcomment]
C:\strawberry\perl\lib\CORE/win32.h:387:33: warning: "/*" within comment [-Wcomment]
c\tree.c: In function 'resolve_network':
c\tree.c:173:46: error: 'AI_V4MAPPED' undeclared (first use in this function)
c\tree.c:173:46: note: each undeclared identifier is reported only once for each function it appears in
c\tree.c: In function 'merge_records':
c\tree.c:557:9: warning: implicit declaration of function 'inet_ntop' [-Wimplicit-function-declaration]
error building dll file from 'c/tree.c' at C:/strawberry/perl/lib/ExtUtils/CBuilder/Platform/Windows.pm line 130.
-> FAIL Installing MaxMind::DB::Writer failed. See C:\Users\manish.m\.cpanm\work\1406179481.5480\build.log for details. Retry with --force to force install it.

### PR DESCRIPTION
**Pull request by oschwald**
Also fixes compilation problems related to `AI_V4MAPPED`. Closes #7 and #51.

### CODE REVIEW

**Comment by autarch** [comment]
Fixes #57

File: c/tree.c [hunk 1]
```diff
@@ -605,6 +588,24 @@ LOCAL void insert_record_for_network(MMDBW_tree_s *tree,
         other_record = &(node_to_set->right_record);
     }
 
+    if (record_to_set->type == MMDBW_RECORD_TYPE_ALIAS) {
+        MMDBW_record_type type = new_record->type;
+        free_record_value(tree, new_record);
+        if (type == MMDBW_RECORD_TYPE_DATA && is_internal_insert) {
+            // free_record_value(tree, new_record);
```
Comment (autarch) [inline c/tree.c]: Why is this commented out? Should this be deleted?

Comment (oschwald) [inline c/tree.c]: Yeah, that is leftover code that I forgot to delete.
